// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDK2SAHnIUT0rZPhfnu6SYhXO2khsuVOI',
    appId: '1:516568437758:web:7f94cd8f548689da6c66af',
    messagingSenderId: '516568437758',
    projectId: 'mentimeeter-6386a',
    authDomain: 'mentimeeter-6386a.firebaseapp.com',
    storageBucket: 'mentimeeter-6386a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoN-uaDiJz0YQHzlBPNHHHrJwp-n2Jbng',
    appId: '1:516568437758:android:162c58e3f8c736966c66af',
    messagingSenderId: '516568437758',
    projectId: 'mentimeeter-6386a',
    storageBucket: 'mentimeeter-6386a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfn4ZkxielDLBT0PEIHe16B_toHBqfqgI',
    appId: '1:516568437758:ios:127b8e0da65618206c66af',
    messagingSenderId: '516568437758',
    projectId: 'mentimeeter-6386a',
    storageBucket: 'mentimeeter-6386a.firebasestorage.app',
    iosClientId: '516568437758-c00lk9r274pgbri24u2mqalansllc7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentimeeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfn4ZkxielDLBT0PEIHe16B_toHBqfqgI',
    appId: '1:516568437758:ios:127b8e0da65618206c66af',
    messagingSenderId: '516568437758',
    projectId: 'mentimeeter-6386a',
    storageBucket: 'mentimeeter-6386a.firebasestorage.app',
    iosClientId: '516568437758-c00lk9r274pgbri24u2mqalansllc7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentimeeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDK2SAHnIUT0rZPhfnu6SYhXO2khsuVOI',
    appId: '1:516568437758:web:6ceaff2166e62f586c66af',
    messagingSenderId: '516568437758',
    projectId: 'mentimeeter-6386a',
    authDomain: 'mentimeeter-6386a.firebaseapp.com',
    storageBucket: 'mentimeeter-6386a.firebasestorage.app',
  );
}
